name:                hc-turtle
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- turtle

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -fno-ignore-asserts

tests:
  tests-unit:
    source-dirs:         test
    main:                hspec.hs
    dependencies:
    - hspec
    - hc-turtle
