name:                Haskell-Design-Patterns
version:             0.1.0.0

ghc-options:
- -Wall
- -fwarn-redundant-constraints
- -fno-warn-missing-signatures
- -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5
- hspec
- hspec-expectations
- HUnit
- test-hunit-util

library:
  source-dirs: src

tests:
  t:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-Design-Patterns
