name:                misc
version:             0.1.0.0

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- bytestring
- cereal
- containers
- pretty-tree
- protolude
- text

library:
  source-dirs: src

tests:
  t:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - cryptonite
    - hspec
    - hspec-expectations
    - misc
