name:                gibbons-demoor-jones-fun-with-phantom-types
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- hspec
- hspec-expectations
- protolude

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

tests:
  t:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:         *exe-ghc-options
    dependencies:
    - gibbons-demoor-jones-fun-with-phantom-types
