name:                rwsio
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- lens
- mtl
- transformers
- template-haskell

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -fno-ignore-asserts

tests:
  tests-unit:
    source-dirs:         test
    main:                hspec.hs
    dependencies:
    - hspec
    - rwsio

benchmarks:
  benchmarks:
    source-dirs:
    - benchmark
    - test
    main:                Bench.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - hspec
    - rwsio

