name:                hc-dhall
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- dhall
- text

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  m:
    main:                Main.hs
    source-dirs:         app
    ghc-options:         *exe-ghc-options
    dependencies:
    - hc-dhall

tests:
  test:
    main:                hspec.hs
    source-dirs:         test
    ghc-options:         *exe-ghc-options
    dependencies:
    - hc-dhall
    - hspec
    - hspec-expectations
