name:                loh-mcbride-swierstra-lambda-pi
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- haskeline
- mtl
- parsec
- pretty

library:
  source-dirs: src

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  st:
    source-dirs:         app
    main:                MainST.hs
    other-modules:       ""
    ghc-options:         *exe-ghc-options
    dependencies:
    - loh-mcbride-swierstra-lambda-pi

  lp:
    source-dirs:         app
    main:                MainLP.hs
    other-modules:       ""
    ghc-options:         *exe-ghc-options
    dependencies:
    - loh-mcbride-swierstra-lambda-pi

tests:
  t:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - loh-mcbride-swierstra-lambda-pi
